// <auto-generated />
using System;
using AmericaVirtual1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmericaVirtual1.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210318034814_ActualizarTablasPaisesCiudades")]
    partial class ActualizarTablasPaisesCiudades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AmericaVirtual1.Models.Ciudades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaisesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaisesId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Ciudades", b =>
                {
                    b.HasOne("AmericaVirtual1.Models.Paises", null)
                        .WithMany("ListaCiudades")
                        .HasForeignKey("PaisesId");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Paises", b =>
                {
                    b.Navigation("ListaCiudades");
                });
#pragma warning restore 612, 618
        }
    }
}
