// <auto-generated />
using System;
using AmericaVirtual1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmericaVirtual1.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210318060711_InicialDatosClima")]
    partial class InicialDatosClima
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AmericaVirtual1.Models.Ciudades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaisesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaisesId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.DatosClima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CiudadesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Humedad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicadorClima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precipitaciones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperaturaC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vientos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CiudadesId");

                    b.ToTable("DatosClima");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Paises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Ciudades", b =>
                {
                    b.HasOne("AmericaVirtual1.Models.Paises", null)
                        .WithMany("ListaCiudades")
                        .HasForeignKey("PaisesId");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.DatosClima", b =>
                {
                    b.HasOne("AmericaVirtual1.Models.Ciudades", null)
                        .WithMany("ListaDatosClima")
                        .HasForeignKey("CiudadesId");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Ciudades", b =>
                {
                    b.Navigation("ListaDatosClima");
                });

            modelBuilder.Entity("AmericaVirtual1.Models.Paises", b =>
                {
                    b.Navigation("ListaCiudades");
                });
#pragma warning restore 612, 618
        }
    }
}
